version: "3.8"
services:
  db:
    image: postgres:15
    container_name: file_scanner_db
    environment:
      POSTGRES_DB: file_scanner_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  app_user1:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        SERVER_PORT: 8080
    container_name: file_scanner_user1
    environment:
      SPRING_JPA_HIBERNATE_DDL_AUTO: validate
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/file_scanner_db
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
      APP_USER: user1
      SERVER_PORT: 8080
    ports:
      - "8080:8080"
    depends_on:
      - db

  app_user2:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        SERVER_PORT: 8082
    container_name: file_scanner_user2
    environment:
      SPRING_JPA_HIBERNATE_DDL_AUTO: validate
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/file_scanner_db
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
      APP_USER: user2
      SERVER_PORT: 8082
    ports:
      - "8082:8082"
    depends_on:
      - db

volumes:
  pgdata:
